kind: pipeline
name: default

steps:
- name: test
  image: python:3.10
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
  - pip install poetry
  - poetry install
  - poetry run pytest
